# Site settings
title: L's Blog
SEOTitle: L&L的博客 | L's Blog
header-img: img/post-bg-desk.jpg
email: abcllnn@163.com
description: "Every failure is leading towards success."
keyword: "BY, L's Blog, L&L的博客, liliang, L&L, iOS, Apple, iPhone"
url: "http://abcll2018.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/abcll2018/abcll2018.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "仁者乐山,渔者乐水"
sidebar-avatar: /img/avatar-by.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:   bk.ll566.ga
zhihu_username:     L&L
github_username:    abcll2018
facebook_username:  L&L
jianshu_username:   L&L
#twitter_username:   L&L




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: abcll2018

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0    #生成的clientSecret
  repo: abcll2018.github.io    #仓库名称
  owner: abcll2018    #github用户名
  admin: abcll2018
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计



# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "google",
        href: "http://google.com"
    },{
        title: "简书·LL",
        href: "http://www.jianshu.com/u/"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "中钓论坛",
        href: "http://bbs.xingyunit.cn/"
    }
]
